import { mutationGeneric } from "convex/server";
import { v } from "convex/values";
import { createGitHubClient, postComment, createPullRequestReview } from "../../src/lib/github";

interface Finding {
  type: string;
  file: string;
  line?: number;
  message: string;
  severity: string;
}

function formatReviewComment(
  summary: string,
  findings: Finding[],
  reviewTimeMs: number
): string {
  const lines = [
    "## AI Code Review",
    "",
    `**Summary:** ${summary}`,
    "",
    `**Review Time:** ${(reviewTimeMs / 1000).toFixed(1)}s`,
    "",
    "### Findings",
    "",
  ];

  const bySeverity = {
    critical: findings.filter((f) => f.severity === "critical"),
    high: findings.filter((f) => f.severity === "high"),
    medium: findings.filter((f) => f.severity === "medium"),
    low: findings.filter((f) => f.severity === "low"),
  };

  for (const [severity, items] of Object.entries(bySeverity)) {
    if (items.length > 0) {
      const icon = severity === "critical" ? "🔴" : severity === "high" ? "🟠" : severity === "medium" ? "🟡" : "🟢";
      lines.push(`${icon} **${severity.toUpperCase()}** (${items.length})`);
      lines.push("");

      for (const item of items) {
        lines.push(`- **${item.type}** in \`${item.file}\``);
        if (item.line) {
          lines.push(`  - Line ${item.line}: ${item.message}`);
        } else {
          lines.push(`  - ${item.message}`);
        }
        lines.push("");
      }
    }
  }

  lines.push("---");
  lines.push("*Review generated by PR Agent*");

  return lines.join("\n");
}

export const postReviewComment = mutationGeneric({
  args: {
    accessToken: v.string(),
    owner: v.string(),
    repo: v.string(),
    prNumber: v.number(),
    summary: v.string(),
    findings: v.array(v.object({
      type: v.string(),
      file: v.string(),
      line: v.optional(v.number()),
      message: v.string(),
      severity: v.string(),
    })),
    reviewTimeMs: v.number(),
  },
  handler: async (ctx: any, args: any) => {
    try {
      const octokit = createGitHubClient(args.accessToken);
      const commentBody = formatReviewComment(
        args.summary,
        args.findings as Finding[],
        args.reviewTimeMs
      );

      const commentId = await postComment(
        octokit,
        args.owner,
        args.repo,
        args.prNumber,
        commentBody
      );

      // Also create a review with suggestions if there are critical issues
      const criticalCount = (args.findings as Finding[]).filter(
        (f) => f.severity === "critical" || f.severity === "high"
      ).length;

      if (criticalCount > 0) {
        await createPullRequestReview(
          octokit,
          args.owner,
          args.repo,
          args.prNumber,
          `Found ${criticalCount} high-priority issues that should be addressed before merging.`,
          "REQUEST_CHANGES"
        );
      } else {
        await createPullRequestReview(
          octokit,
          args.owner,
          args.repo,
          args.prNumber,
          "Code review completed. Please review the comments.",
          "COMMENT"
        );
      }

      return { success: true, commentId };
    } catch (error) {
      return {
        success: false,
        error: error instanceof Error ? error.message : "Failed to post comment",
      };
    }
  },
});
